BookSpot/Models/ErrorViewModel.cs
namespace BookSpot.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookSpot/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookSpot.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult signup()
        {
            return View();
        }
        public IActionResult login()
        {
            return View();
        }
    }
}

BookSpot/Controllers/BuynowController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookSpot.Controllers
{
    public class BuynowController : Controller
    {

        public ViewResult Buy()
        {
            return View();
        }
    }
}

BookSpot/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookSpot.Controllers
{
    public class CategoryController : Controller
    {
        public ViewResult Academic()
        {
            return View();
        }

        public ViewResult No_academic()
        {
            return View();
        }
    }
}

BookSpot/Controllers/HomeController.cs
using BookSpot.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookSpot.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ViewResult Contact()
        {
            return View();
        }

        public ViewResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookSpot/Controllers/SellController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookSpot.Controllers
{
    public class SellController : Controller
    {
        public ViewResult Sell()
        {
            return View();
        }
    }
}

BookSpot/Views/Buynow/Buy.cshtml
@{
    ViewData["Title"] = "Buy your books";
}
<div class="container pt-4">
  <div class="row p-3" style="background-color:#f7d4d4">
    <div class="col">
      <img src="~/img/sellers/2.jpg" class="card-img-top" alt="..." style="height: 400px">
    </div>
    <div class="col my-auto">
      <h1 class="card-title">Find Me</h1>
      <p class="card-text" style="font-size: 25px">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <h4 class="card-text">Rs. 200</h4>    
      <a href="#" class="btn btn-success">Buy now</a>   
  </div>
  </div>
</div>

<div class="container pt-4">
<div class="row">
    <h1>Sypnosis</h1>
    <p>As a creative force, student of the human heart and soul, and champion of living the life you want, Oprah Winfrey stands alone. Over the years, she has made history with a legendary talk show - the highest-rated program of its kind, launched her own television network, become the nation's only African-American billionaire, and been awarded both an honorary degree by Harvard University and the Presidential Medal of Freedom. From all her experiences, she has gleaned life lessons—which, for fourteen years, she's shared in O, The Oprah Magazine's widely popular "What I Know For Sure" column, a monthly source of inspiration and revelation.</p>
    </div>    

</div>

BookSpot/Views/Category/Academic.cshtml
@{
    ViewData["Title"] = "Acadamic";

}
<h2 class="mt-4 text-center">Buy Used Acadamic Related Book </h2>
<div class="row">
    <div class="col-md-3">
    <div class="card" style="width: 15rem;">
  <img src="~/img/acadamic/english.jpg" class="card-img-top" alt="..." style="height: 20rem">
  <div class="card-body">
    <h5 class="card-title">English(X)</h5>
    <p class="card-text">Rs. 100</p>
    <a href="#" class="btn btn-success">Add To Cart</a>
  </div>
</div>
</div>
<div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src= "~/img/acadamic/social.jpg" class="card-img-top" alt="..." style="height: 20rem" >
  <div class="card-body">
    <h5 class="card-title">Social</h5>
    <p class="card-text">Rs 150</p>
    <a href="#" class="btn btn-success">Add To Cart</a>
  </div>
</div>
</div>
<div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src="~/img/acadamic/science.jpg" class="card-img-top" alt="..." style="height: 20rem">
  <div class="card-body">
    <h5 class="card-title">Science</h5>
    <p class="card-text">Rs.200</p>
    <a href="#" class="btn btn-success">Add To Cart</a>
  </div>
  </div>
  </div>
  <div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src="~/img/acadamic/math.jpg" class="card-img-top" alt="..." style="height: 20rem">
  <div class="card-body">
    <h5 class="card-title"> Math</h5>
    <p class="card-text">Rs.200</p>
    <a href="#" class="btn btn-success">Add To Cart</a>
  </div>
</div>
</div>
</div>

BookSpot/Views/Category/No_academic.cshtml
@{
    ViewData["Title"] = "Non-academic";
}

@{
    ViewData["Title"] = "Acadamic";

}

<h2 class="mt-4 text-center">Buy any used Books</h2>
<div class="row">
    <div class="col-md-3">
    <div class="card" style="width: 15rem;">
  <img src="~/img/sellers/1.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">A little life</h5>
    <p class="card-text">Rs. 200</p>
    <a href="#" class="btn btn-success">Add To Cart</a>
  </div>
</div>
</div>
<div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src= "~/img/sellers/2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Find Me</h5>
    <p class="card-text">Rs 300</p>
    <a href="#" class="btn btn-success">Add To Cart</a>
  </div>
</div>
</div>
<div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src="~/img/sellers/3.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Twelve and Half</h5>
    <p class="card-text">Rs.350</p>
    <a href="#" class="btn btn-success">Add To Cart</a>
  </div>
  </div>
  </div>
  <div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src="~/img/sellers/4.png" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"> Subconscious Mind</h5>
    <p class="card-text">Rs.200</p>
    <a href="#" class="btn btn-success">Add To Cart</a>
  </div>
</div>
</div>

</div>

BookSpot/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="container">
    <h1 class="text-center">
        About BookSpot:
    </h1>

    <p>"Book Spot" is a platform where users can get access to the books published all around the world easily at low price
        or no cost mechanism.As we all know, books are a collection of wise words and knowledge.Rather than stacking the books 
        and filling it with dirt,we purpose to pass the book around or let us say pass the knowledge and wisdom around.
    </p>
    <p>“Quality Education” is enlisted by the UN as the 4th goal for sustainable development to
transform our world. But education is by no means accessible to everyone and is not
affordable to all hierarchies of people. The purpose of this platform is to reduce cost on basic
component of the education system ie. the book. Education is a subjective word and doesn’t
necessarily mean going to school and learning from the teachers. Research has found that
students who read other books than just the one prescribed by their education institution are
more creative and have the skills to tackle real words problems. And by quality education we
mean this.</p>
<p>
Also, technology is something we cannot ignore and is booming at a high speed. From
“Book Spot” we intend to bring people together through responsible use of technology. Also
the technology will be working on a transparent layer and all the data shall be open sourced
to the people.</p>

    <h3>Contact:</h3>
    <p><i class="fa-solid fa-phone"></i>&nbsp;+977 - 9898989898</p>
    <p><i class="fa-solid fa-envelope"></i>&nbsp;bookspot@gmail.com</p>

</div>

BookSpot/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}


<h1 class="text-center">Contact <span style="color: green;">Us</span></h1>
<div class="container">
  <div class="row">
    <div class="col">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28247.794686665915!2d85.30062468562456!3d27.748937577920934!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb192b9cada64d%3A0xdf67e83763747500!2z4KSX4KWL4KSC4KSX4KSs4KWBLCA0NDYwMA!5e0!3m2!1sne!2snp!4v1655633225237!5m2!1sne!2snp" width="500" height="350" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
    <div class="col">
      <div class="mb-3">
         <label for="name" class="form-label">Name</label>
         <input type="text" class="form-control" id="name">
    </div>
    <div class="mb-3">
         <label for="name" class="form-label">Email</label>
         <input type="text" class="form-control" id="email">
    </div>
    <div class="mb-3">
  <label for="message" class="form-label">Your Message</label>
  <textarea class="form-control" id="message" rows="3"></textarea>
</div>
 <div class="mb-3">
 <a href="#" class="btn btn-success">Send</a>
</div>
    </div>
   </div>
</div>

BookSpot/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<head>
    <link rel="stylesheet" href="~/css/sell.css" />
</head>
<div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/img/first_page.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/img/second_page.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/img/third_page.png" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<h5 class="mt-4">Best Sellers</h5>
<div class="row">
    <div class="col-md-3">
    <div class="card" style="width: 15rem;">
  <img src="~/img/sellers/2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Find Me</h5>
    <p class="card-text">Rs. 200</p>
    <a asp-controller="Buynow" asp-action="Buy" class="btn btn-success">Buy Now</a>
  </div>
</div>
</div>
<div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src= "~/img/sellers/1.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">A little Life</h5>
    <p class="card-text">Rs 300</p>
    <a href="#" class="btn btn-success">Buy Now</a>
  </div>
</div>
</div>
<div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src="~/img/sellers/3.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Twelve and Half</h5>
    <p class="card-text">Rs.350</p>
    <a href="#" class="btn btn-success">Buy Now</a>
  </div>
  </div>
  </div>
  <div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src="~/img/sellers/4.png" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"> Subconscious Mind</h5>
    <p class="card-text">Rs.200</p>
    <a href="#" class="btn btn-success">Buy Now</a>
  </div>
</div>
</div>

</div>
<h5 class="mt-4">New Arrivals</h5>
<div class="row">
    <div class="col-md-3">
    <div class="card" style="width: 15rem;">
  <img src="~/img/new_arrival/new_arrival_1.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Discover Your Destiny</h5>
    <p class="card-text">Rs. 200</p>
    <a href="#" class="btn btn-success">Buy Now</a>
  </div>
</div>
</div>
<div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src= "~/img/new_arrival/new_arrival_2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Men We Reaped</h5>
    <p class="card-text">Rs 300</p>
    <a href="#" class="btn btn-success">Buy Now</a>
  </div>
</div>
</div>
<div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src="~/img/new_arrival/new_arrival_3.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Lessons For Life</h5>
    <p class="card-text">Rs.350</p>
    <a href="#" class="btn btn-success">Buy Now</a>
  </div>
  </div>
  </div>
  <div class="col-md-3">
<div class="card" style="width: 15rem;">
  <img src="~/img/new_arrival/new_arrival_4.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Better To Have Gone</h5>
    <p class="card-text">Rs.200</p>
    <a href="#" class="btn btn-success">Buy Now</a>
  </div>
</div>
</div>
</div>


        <div class="row img_body mt-5">
            <div class="col">
                <img src="~/img/Sell-books-online.jpg" style="width: 100%; height: 400px;"/>
                <div class="button_group">
                <h1 class="text-center color_text">
                    Want to Sell Your Books?
                </h1>
                <div class="row justify-content-md-center mt-5">
                    <a href="~/Sell/Sell" class="btn btn-outline-success btn_text">Click Here</a>
                </div>
                </div>
            </div>  
        </div>


</div>

BookSpot/Views/Sell/Sell.cshtml
@{
        ViewData["Title"] = "Sell";
    }
    <div class="row justify-content-md-center">
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <h3>Sell your Book</h3>
            <hr/>
            <form method = "post">
                <div class="mb-3">
            <label for="name" class="form-label">Seller Name</label>
            <input type="text" class="form-control" id="name" >
    </div>
          <div class="mb-3">
            <label for="bookName" class="form-label">Book Name</label>
            <input type="text" class="form-control" id="bookName" >
    </div>
      <div class="mb-3">
            <label for="bookDesc" class="form-label">Book Description</label>
            <input type="text" class="form-control" id="bookDesc" >
     </div>  
     
     

     <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="text" class="form-control" id="price" >
     </div>
     <div class="mb-3">
            <label for="bookImage" class="form-label">Choose File</label>
            <input type="file" class="form-control" id="bookImage" >
     </div>
    <hr/>
    <button type="submit" class="btn btn-primary">Upload</button>
    <hr />
     
 
            </form>
        </div>

    </div>

</div>
</div>

BookSpot/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookSpot.styles.css" asp-append-version="true" />
    

    <script src="https://kit.fontawesome.com/9c7c808cd1.js" crossorigin="anonymous"></script>
</head>
<body>
<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/img/book.png" alt="" width="30" height="35" >BookSpot</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                  <div class="container-fluid">
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="width: 500px">
      <button class="btn btn-outline-success" type="submit">
          <i class="fa-solid fa-magnifying-glass"></i>
      </button>

    </form>
  </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
 
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        
                        <li class="nav-item">
                         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item text-dark" href="~/Category/Academic">Academic</a></li>
            <li><a class="dropdown-item text-dark" href="~/Category/No_academic">Non-Academic</a></li>
       
          </ul>
        </li>
                       
                        <li class = "nav-item">
                         <a class= "nav-link text-light btn btn-outline-success" asp-area="light" asp-controller="Auth" asp-action="Login">Login </a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Auth" asp-action="signup">Register</a>
                        </li> 
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center" >
            &copy; 2022 - BookSpot <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>